targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/models/**.dart
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false 