// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtzL122qUzrGAgFvPio81wJLTDmRAKwDA',
    appId: '1:59318045507:web:0a0e76fc3fc7c0dc19bdf6',
    messagingSenderId: '59318045507',
    projectId: 'gamifying-k-12-education',
    authDomain: 'gamifying-k-12-education.firebaseapp.com',
    storageBucket: 'gamifying-k-12-education.firebasestorage.app',
    measurementId: 'G-R8D6NTY1B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbgmDnqbKUyk_ZFoISxfQg7jW6T_-y2og',
    appId: '1:59318045507:android:0b8ce6d5c28b257819bdf6',
    messagingSenderId: '59318045507',
    projectId: 'gamifying-k-12-education',
    storageBucket: 'gamifying-k-12-education.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpm4edfitadbPr8RKeXivUIwpF2en32Y0',
    appId: '1:59318045507:ios:2d54ed380dbafd8a19bdf6',
    messagingSenderId: '59318045507',
    projectId: 'gamifying-k-12-education',
    storageBucket: 'gamifying-k-12-education.firebasestorage.app',
    iosBundleId: 'dev.lovable.learnPlayLevelUpFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpm4edfitadbPr8RKeXivUIwpF2en32Y0',
    appId: '1:59318045507:ios:2d54ed380dbafd8a19bdf6',
    messagingSenderId: '59318045507',
    projectId: 'gamifying-k-12-education',
    storageBucket: 'gamifying-k-12-education.firebasestorage.app',
    iosBundleId: 'dev.lovable.learnPlayLevelUpFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtzL122qUzrGAgFvPio81wJLTDmRAKwDA',
    appId: '1:59318045507:web:c4ca0f9705a2206719bdf6',
    messagingSenderId: '59318045507',
    projectId: 'gamifying-k-12-education',
    authDomain: 'gamifying-k-12-education.firebaseapp.com',
    storageBucket: 'gamifying-k-12-education.firebasestorage.app',
    measurementId: 'G-9T2G7K58PX',
  );
}
